### PR TITLE
Fix #65

### LINKED ISSUE #65: Bug: cannot find function concensus
Hallihallo @KlausVigo,

Thanks for accepting my Pull Request and fixing the `densiTree` bug!

The test I added indeed work when run (tested on a clone of this repo at the `devel` branch). However, as a user, something goes wrong. I will first show what goes right:

```{r}
# Install newest version
devtools::install_github("KlausVigo/phangorn", branch = "devel")

# Create some trees
tree_1 <- ape::read.tree(text = "((A:2,B:2):1, C:3);")
tree_2 <- ape::read.tree(text = "((A:1,C:1):2, B:3);")
trees <- c(tree_1, tree_2)

# Plotting with a consensus works great
phangorn::densiTree(trees, consensus = LETTERS[1:3])
```

However, plotting with a NULL consensus fails:

```
# Plotting with a NULL consensus fails
phangorn::densiTree(trees)
```

with error message:

```
Error in consensus(tree) : could not find function "consensus"
```

I hope you know what causes this and you can fix it with ease :+1:

Tschuess, @richelbilderbeek

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Allows user to call `phangorn::densiTree` without doing `library(ape)` first. In this way, it always works.

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
@KlausVigo: what do you think about this Pull Request?

**Comment by KlausVigo** [comment]
@richelbilderbeek, thanks a again for reminding. Do you have any idea why this is needed. `phangorn` depends on `ape` and imports all exported functions, so it seems to work just fine on my machine. Is this happening when you call it from your packages or does `consensus` gets redefined by some other package?

**Comment by richelbilderbeek** [comment]
> Do you have any idea why this is needed?

I do have the idea that adding namespaces is more and more recommended by `R CMD`, @lintr-bot and [goodpractice](https://github.com/MangoTheCat/goodpractice/issues/41).

Except for that, sadly, I do not remember anymore what caused my problem. I tried this code ...

```r
phangorn::densiTree(c(ape::rcoal(3)))
```

... but that just works fine. I do know there is a reason I added this, maybe on an AppVeyor build. Dumb me to hand in such a half-baked Pull Request :slightly_frowning_face: 

> Is this happening when you call it from your packages or does consensus gets redefined by some other package?

No, as far as I could see, this was not the problem.

**Comment by richelbilderbeek** [comment]
Thanks @KlausVigo for the trust :+1:

**Pull request merged**
